package descent.launching;

/**
 *  An interface that listens to events generated by the rebuild builder. This
 *  class is intended to be subclassed by clients.
 *
 * @author Robert Fraser
 */
public interface IDebuildEventListener
{
	/**
	 * Called when a new build is started.
	 * 
	 * @param build the build that started
	 */
	public void buildStarted(IExecutableTarget build);
	
	/**
	 * Called when a build fails (due to errors, etc.)
	 * 
	 * @param build the build that failed
     * @param e     the exception that caused the build to fail
	 */
	public void buildFailed(IExecutableTarget build);
	
	/**
	 * Called when a build is cancelled by the user.
	 * 
	 * @param build the build that was cancelled
	 */
	public void buildCancelled(IExecutableTarget build);
	
	/**
	 * Called when a build is succesful.
	 * 
	 * @param build              the build that succeeded
	 * @param executableFilePath the path to the generated executable file
	 */
	public void buildSucceeded(IExecutableTarget build, 
			String executableFilePath);
}
